// Driver test bench -- Nucleo-H753ZI.
//
// Exercises the ICM-42688-P 6-axis IMU driver (shared/sensors/icm42688.*) over
// I2C1 and prints samples over USART3 (ST-Link Virtual COM Port, 115200 8N1).
//
// Print path uses HAL_UART_Transmit directly -- USART3 is left as the default
// CubeMX "HAL" driver mode (not CMSIS Driver). The HAL handle `huart3` is
// generated by MX_USART3_UART_Init() and declared in main.h via usart.h.
//
// Expected over VCP:
//   ICM42688 ready
//   AX=    12 AY=  -134 AZ=  16320  GX=    -3 GY=     8 GZ=    -2
//   ...

#include "main.h"

#include "cmsis_i2c_bus.hpp"
#include "icm42688.hpp"

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>

// NOLINTNEXTLINE(readability-identifier-naming)
extern ARM_DRIVER_I2C Driver_I2C1;
// NOLINTNEXTLINE(readability-identifier-naming)
extern UART_HandleTypeDef huart3;
// NOLINTNEXTLINE(readability-identifier-naming)
extern I2C_HandleTypeDef hi2c1;

namespace {

    constexpr uint32_t TX_TIMEOUT_MS = 100U;

    void print(const char* msg) {
        const auto len = static_cast<uint16_t>(std::strlen(msg));
        // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
        HAL_UART_Transmit(&huart3, reinterpret_cast<const uint8_t*>(msg), len, TX_TIMEOUT_MS);
    }

    void print_sample(const ICM42688Result& s) {
        std::array<char, 96> buf{};
        // NOLINTNEXTLINE(cppcoreguidelines-pro-type-vararg,hicpp-vararg)
        const int n = std::snprintf(buf.data(), buf.size(), "AX=%6d AY=%6d AZ=%6d  GX=%6d GY=%6d GZ=%6d\r\n", s.accel_x,
                                    s.accel_y, s.accel_z, s.gyro_x, s.gyro_y, s.gyro_z);
        if (n > 0) {
            // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
            HAL_UART_Transmit(&huart3, reinterpret_cast<const uint8_t*>(buf.data()), static_cast<uint16_t>(n),
                              TX_TIMEOUT_MS);
        }
    }

    // Probes every valid 7-bit I2C address (0x08..0x77) with a 1-byte read.
    // ACK -> device present, NACK -> empty slot. Prints a one-line summary.
    void i2c_scan(CmsisI2CBus& bus) {
        std::array<char, 16> hex{};
        std::array<uint8_t, 16> found{};
        uint8_t found_count = 0U;

        for (uint8_t addr = 0x08U; addr <= 0x77U; ++addr) {
            uint8_t dummy = 0U;
            if (bus.read(addr, &dummy, 1U)) {
                if (found_count < found.size()) {
                    found[found_count++] = addr;
                }
            }
        }

        print("CMSIS scan: ");
        if (found_count == 0U) {
            print("no devices found\r\n");
        } else {
            for (uint8_t i = 0U; i < found_count; ++i) {
                // NOLINTNEXTLINE(cppcoreguidelines-pro-type-vararg,hicpp-vararg)
                const int n = std::snprintf(hex.data(), hex.size(), "0x%02X ", found[i]);
                if (n > 0) {
                    // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
                    HAL_UART_Transmit(&huart3, reinterpret_cast<const uint8_t*>(hex.data()), static_cast<uint16_t>(n),
                                      TX_TIMEOUT_MS);
                }
            }
            print("\r\n");
        }
    }

    // Direct-HAL scan. Bypasses CmsisI2CBus / Driver_I2C1 to isolate whether
    // the issue is the CMSIS-Driver layer or the underlying HAL peripheral.
    void hal_i2c_scan() {
        std::array<char, 16> hex{};
        std::array<uint8_t, 16> found{};
        uint8_t found_count = 0U;

        for (uint8_t addr = 0x08U; addr <= 0x77U; ++addr) {
            // HAL takes 8-bit shifted address; 3 retries, 10 ms timeout.
            if (HAL_I2C_IsDeviceReady(&hi2c1, static_cast<uint16_t>(addr << 1U), 3U, 10U) == HAL_OK) {
                if (found_count < found.size()) {
                    found[found_count++] = addr;
                }
            }
        }

        print("HAL scan:   ");
        if (found_count == 0U) {
            print("no devices found\r\n");
            return;
        }
        for (uint8_t i = 0U; i < found_count; ++i) {
            // NOLINTNEXTLINE(cppcoreguidelines-pro-type-vararg,hicpp-vararg)
            const int n = std::snprintf(hex.data(), hex.size(), "0x%02X ", found[i]);
            if (n > 0) {
                // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
                HAL_UART_Transmit(&huart3, reinterpret_cast<const uint8_t*>(hex.data()), static_cast<uint16_t>(n),
                                  TX_TIMEOUT_MS);
            }
        }
        print("\r\n");
    }

} // namespace

extern "C" void app_main(void) {
    static CmsisI2CBus i2c{&Driver_I2C1, HAL_GetTick};
    static ICM42688 imu{};

    // Scan with HAL directly first -- hi2c1 was initialized by MX_I2C1_Init()
    // in main.c before app_main() ran, so the peripheral is already live.
    hal_i2c_scan();

    if (!i2c.init()) {
        print("I2C1 init FAILED\r\n");
        while (true) {
            HAL_Delay(1000);
        }
    }

    i2c_scan(i2c);

    if (!imu.init(&i2c)) {
        print("ICM42688 init FAILED -- check wiring (SDA/SCL, AD0=GND for 0x68) and power.\r\n");
        while (true) {
            HAL_Delay(1000);
        }
    }

    print("ICM42688 ready\r\n");

    while (true) {
        if (auto sample = imu.read_sample()) {
            print_sample(*sample);
        } else {
            print("read_sample FAILED\r\n");
        }
        HAL_Delay(100);
    }
}
