//! Generates, from schema.json (itself emitted from the bolt/wire/payloads.hpp
//! WIRE(...) annotations):
//!   - schema_gen.rs   : the units/scales/gates table (bolt_codec::schema)
//!   - payloads_gen.rs : the wire structs + their byte-offset `decode()`
//! so the Rust side is never a hand-maintained mirror of the flight header - it
//! is generated from the same single source and can never drift on layout.

use std::{collections::BTreeMap, env, fs, path::Path};

use serde_json::Value;

fn s(v: &Value, k: &str) -> String {
    v.get(k).and_then(Value::as_str).unwrap_or("").replace('\\', "\\\\").replace('"', "\\\"")
}
fn f(v: &Value, k: &str) -> f64 {
    v.get(k).and_then(Value::as_f64).unwrap_or(0.0)
}
fn u(v: &Value, k: &str) -> u64 {
    v.get(k).and_then(Value::as_u64).unwrap_or(0)
}

// PascalCase -> snake_case (BtcEnv -> btc_env, Exp1Spectrum -> exp1_spectrum).
fn snake(pascal: &str) -> String {
    let mut out = String::new();
    for (i, c) in pascal.chars().enumerate() {
        if c.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.extend(c.to_lowercase());
    }
    out
}

// Built-in C scalar (as reflection spells it) -> (rust type, le-reader fn or
// "" for a byte); enums are deliberately absent, see scalar()
fn builtin(ctype: &str) -> Option<(&'static str, &'static str)> {
    Some(match ctype {
        "unsigned char" => ("u8", ""),
        "signed char" => ("i8", ""),
        "short" => ("i16", "i16le"),
        "unsigned short" => ("u16", "u16le"),
        "int" => ("i32", "i32le"),
        "unsigned int" => ("u32", "u32le"),
        _ => return None,
    })
}

fn reader_for(rty: &str) -> &'static str {
    match rty {
        "u8" | "i8" => "",
        "i16" => "i16le",
        "u16" => "u16le",
        "i32" => "i32le",
        "u32" => "u32le",
        other => panic!("build.rs: no le-reader for enum underlying type `{other}`"),
    }
}

// C type -> (rust type, le-reader fn). Enum field types resolve against the
// schema's own `enums` list - a hand-kept name list here broke the build on
// every new wire enum
fn scalar(ctype: &str, enums: &BTreeMap<String, String>) -> (String, String) {
    if let Some((rty, reader)) = builtin(ctype) {
        return (rty.to_string(), reader.to_string());
    }
    if let Some(underlying) = enums.get(ctype) {
        return (underlying.clone(), reader_for(underlying).to_string());
    }
    panic!("build.rs: unmapped ctype `{ctype}` - neither a built-in scalar nor an enum in schema.json")
}

// (rust field type, reader expression) for one schema field.
fn field_rust(fld: &Value, enums: &BTreeMap<String, String>) -> (String, String) {
    let ctype = fld.get("ctype").and_then(Value::as_str).unwrap();
    let off = u(fld, "byte_offset");
    let count = u(fld, "count");
    if let Some(br) = ctype.find('[') {
        let (bty, _) = scalar(ctype[..br].trim(), enums);
        (format!("[{bty}; {count}]"), format!("arr_{bty}::<{count}>(b, {off})"))
    } else {
        let (rty, reader) = scalar(ctype, enums);
        let expr = if reader.is_empty() { format!("b[{off}]") } else { format!("{reader}(b, {off})") };
        (rty, expr)
    }
}

fn main() {
    // Single source of truth: interfaces/tools/generated/schema.json, emitted by
    // interfaces/tools/schemagen from the bolt/wire WIRE(...)/PACKET(...) annotations.
    // Path is relative to this crate (telemetry-tools/crates/bolt-codec).
    const SCHEMA: &str = "../../../interfaces/tools/generated/schema.json";
    println!("cargo:rerun-if-changed={SCHEMA}");

    let schema: Value =
        serde_json::from_str(&fs::read_to_string(SCHEMA).expect("schema.json missing")).unwrap();
    let payloads = schema["payloads"].as_array().unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    // enum name -> underlying wire type, straight from the schema
    let enums: BTreeMap<String, String> = schema["enums"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| (s(e, "name"), s(e, "underlying")))
        .collect();

    // --- schema table (units/scales/gates) -------------------------------
    let mut sc = String::from("// @generated by build.rs from schema.json - do not edit.\n");
    sc.push_str("pub static SCHEMA: &[PayloadSchema] = &[\n");
    for p in payloads {
        sc.push_str(&format!("    PayloadSchema {{ name: \"{}\", size: {}, fields: &[\n", s(p, "name"), u(p, "size")));
        for fld in p["fields"].as_array().unwrap() {
            sc.push_str(&format!(
                "        FieldSchema {{ name: \"{}\", ctype: \"{}\", byte_offset: {}, count: {}, \
                 unit: \"{}\", scale: {:?}, offset: {:?}, gate: \"{}\", desc: \"{}\" }},\n",
                s(fld, "name"), s(fld, "ctype"), u(fld, "byte_offset"), u(fld, "count"),
                s(fld, "unit"), f(fld, "scale"), f(fld, "offset"), s(fld, "gate"), s(fld, "desc"),
            ));
        }
        sc.push_str("    ] },\n");
    }
    sc.push_str("];\n");
    fs::write(Path::new(&out_dir).join("schema_gen.rs"), sc).unwrap();

    // --- wire structs + decode() -----------------------------------------
    let mut pg = String::from("// @generated by build.rs from schema.json - do not edit.\n");
    for p in payloads {
        let name = s(p, "name");
        let rname = name.strip_prefix("Payload").unwrap_or(&name);
        let fields = p["fields"].as_array().unwrap();

        pg.push_str(&format!("#[derive(Debug, Clone, Copy, Serialize)]\npub struct {rname} {{\n"));
        for fld in fields {
            pg.push_str(&format!("    pub {}: {},\n", s(fld, "name"), field_rust(fld, &enums).0));
        }
        pg.push_str("}\n");

        pg.push_str(&format!("impl {rname} {{\n    pub fn decode(b: &[u8]) -> Self {{\n        Self {{\n"));
        for fld in fields {
            pg.push_str(&format!("            {}: {},\n", s(fld, "name"), field_rust(fld, &enums).1));
        }
        pg.push_str("        }\n    }\n}\n\n");
    }
    fs::write(Path::new(&out_dir).join("payloads_gen.rs"), pg).unwrap();

    // --- PayloadType enum + from_u8 + name (from the reflected C++ enum) --
    let types = schema["types"].as_array().unwrap();
    let mut tg = String::from("// @generated by build.rs from schema.json - do not edit.\n");
    tg.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]\n#[repr(u8)]\npub enum PayloadType {\n");
    for t in types {
        tg.push_str(&format!("    {} = {},\n", s(t, "name"), u(t, "value")));
    }
    tg.push_str("}\n\nimpl PayloadType {\n    #[must_use]\n    pub fn from_u8(v: u8) -> Option<PayloadType> {\n");
    tg.push_str("        Some(match v {\n");
    for t in types {
        tg.push_str(&format!("            {} => PayloadType::{},\n", u(t, "value"), s(t, "name")));
    }
    tg.push_str("            _ => return None,\n        })\n    }\n\n");
    tg.push_str("    // Short stable name for the manifest / UI grouping.\n    #[must_use]\n");
    tg.push_str("    pub fn name(self) -> &'static str {\n        match self {\n");
    for t in types {
        tg.push_str(&format!("            PayloadType::{} => \"{}\",\n", s(t, "name"), snake(&s(t, "name"))));
    }
    tg.push_str("        }\n    }\n\n");
    // schema_name (layout struct) + source (emitting node), from the PACKET annotations.
    tg.push_str("    #[must_use]\n    pub fn schema_name(self) -> &'static str {\n        match self {\n");
    for t in types {
        tg.push_str(&format!("            PayloadType::{} => \"{}\",\n", s(t, "name"), s(t, "layout")));
    }
    tg.push_str("        }\n    }\n\n");
    tg.push_str("    #[must_use]\n    pub fn source(self) -> &'static str {\n        match self {\n");
    for t in types {
        tg.push_str(&format!("            PayloadType::{} => \"{}\",\n", s(t, "name"), s(t, "node").to_lowercase()));
    }
    tg.push_str("        }\n    }\n}\n");
    fs::write(Path::new(&out_dir).join("types_gen.rs"), tg).unwrap();

    // --- enum byte->name lookups (from schema["enums"]) ------------------
    // Every WIRE(.desc) annotated enum - downlink field enums (GapReason,
    // NodeId, BootReason) and the uplink command set (CommandOpcode,
    // CommandAckStatus) - so the ground model stops hand-mirroring them.
    let fn_name = |name: &str| -> Option<&'static str> {
        Some(match name {
            "GapReason" => "gap_reason",
            "BootReason" => "boot_reason",
            "NodeId" => "node_name",
            "CommandOpcode" => "command_name",
            "CommandAckStatus" => "ack_status_name",
            "TestResult" => "test_result_name",
            _ => return None,
        })
    };
    let mut eg = String::from("// @generated by build.rs from schema.json - do not edit.\n");
    if let Some(enums) = schema["enums"].as_array() {
        for e in enums {
            let Some(fname) = fn_name(&s(e, "name")) else { continue };
            eg.push_str(&format!("pub fn {fname}(v: u8) -> &'static str {{\n    match v {{\n"));
            for val in e["values"].as_array().unwrap() {
                eg.push_str(&format!("        {} => \"{}\",\n", u(val, "value"), s(val, "name").to_lowercase()));
            }
            eg.push_str("        _ => \"unknown\",\n    }\n}\n");

            // Danger flag for the uplink command set - single source is the
            // `.danger` annotation, so command.rs and the extension stop hardcoding it.
            if s(e, "name") == "CommandOpcode" {
                let hot: Vec<String> = e["values"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .filter(|v| v["danger"].as_bool().unwrap_or(false))
                    .map(|v| u(v, "value").to_string())
                    .collect();
                if hot.is_empty() {
                    eg.push_str("pub fn command_danger(_v: u8) -> bool { false }\n");
                } else {
                    eg.push_str(&format!(
                        "pub fn command_danger(v: u8) -> bool {{ matches!(v, {}) }}\n",
                        hot.join(" | ")
                    ));
                }
            }
        }
    }
    fs::write(Path::new(&out_dir).join("enums_gen.rs"), eg).unwrap();
}
