#pragma once

#include "can_transport.hpp"

// bxCAN implementation for STM32L4xx targets (no FDCAN, max 8 bytes per frame).
// Fragments `data` into 8-byte CAN frames:
//   byte[0] = (frame_index << 4) | frame_count  - 4 bits each, max 15 frames (105 bytes)
//   bytes[1..7] = payload chunk (7 bytes, zero-padded on last frame)
// Receiver (BTC) must reassemble using frame_count in byte[0].
// Requires hcan1 generated by CubeMX.
class BxcanTransport final : public CanTransport {
  public:
    void send(uint32_t id, const uint8_t* data, uint8_t len) override;
};
